# Site settings
title: Dronezz - Property Management via Aerial Drone Imaging, Image Processing, and Change Detection
description: Developed for ECE Capstone (Georgia Institute of Technology)

# author:
#   name: Alexander Fache
#   bio: 'Georgia Tech ECE'
#   github: alexanderfache6

github:
  is_project_page: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
